spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_iamtheboss_db
    username: guest
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update  # adjust this to your preference


spring.jpa:
  show-sql: true
  hibernate.ddl=auto: create-drop

#spring.datasource:
#  platform: h2
#  url: jdbc:h2:mem:ecommerce-app
#
#spring.h2.console.enabled: true

spring.security.oauth2.resourceserver.jwt.jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com
